version: '3'
services:
  exocom0.22.1:
    image: 'originate/exocom:0.22.1'
    command: bin/exocom
    container_name: exocom0.22.1
    environment:
      ROLE: exocom
      PORT: $EXOCOM_PORT
      SERVICE_ROUTES: '[{"role":"web","receives":null,"sends":null}]'
  web:
    build: ../web
    container_name: web
    command: node server.js
    environment:
      ROLE: web
      EXOCOM_HOST: exocom0.22.1
      EXOCOM_PORT: $EXOCOM_PORT
    depends_on:
      - exocom0.22.1
