name: shared-dependency-application
description: Demonstrates basic Exosphere application startup
version: '1.0'

dependencies:
  - name: exocom
    version: 0.22.1
  - name: mongo
    version: 3.4.0
    config:
      ports:
        - '5000:5000'
      volumes:
        - '{{EXO_DATA_PATH}}:user/data/db'
      online-text: 'waiting for connections'
      dependency-environment:
        DB_NAME: 'test-db'
      service-environment:
        COLLECTION_NAME: 'test-collection'

services:
  public:
    mongo:
      location: ./mongo
    html-server:
      location: ./html-server
  private:
    users:
      namespace: mongo
      location: ./mongo-service