version: '3'
services:
  exocom0.22.1:
    image: 'originate/exocom:0.22.1'
    command: bin/exocom
    container_name: exocom0.22.1
    environment:
      ROLE: exocom
      PORT: $EXOCOM_PORT
      SERVICE_ROUTES: >-
        [{"role":"web","receives":["users.listed","users.created"],"sends":["users.list","users.create"]},{"role":"users","receives":["mongo.list","mongo.create"],"sends":["mongo.listed","mongo.created"],"namespace":"mongo"}]
  web:
    build: ../web-server
    container_name: web
    command: node_modules/.bin/lsc server.ls
    ports:
      - '4000:4000'
    environment:
      ROLE: web
      EXOCOM_HOST: exocom0.22.1
      EXOCOM_PORT: $EXOCOM_PORT
    depends_on:
      - exocom0.22.1
  users:
    build: ../mongo-service
    container_name: users
    command: node_modules/exoservice/bin/exo-js
    environment:
      ROLE: users
      EXOCOM_HOST: exocom0.22.1
      EXOCOM_PORT: $EXOCOM_PORT
    depends_on:
      - exocom0.22.1
