# Application Name
# Only lowercase alphanumeric character(s) separated by a single hyphen are allowed
name:

# Configuration for locally running the application
local:
  # Dependencies
  dependencies:
    <id>:
      image:
      persist:
      environment-variables:

  # Map of environment variables to pass to every service
  environment-variables:
    NAME: value

  # Secrets
  secrets:
