name: runtime crasher
description: for testing behavior when a service crashes at runtime
version: '1.0'

dependencies:
  - name: exocom
    version: 0.22.1

services:
  public:
    crasher:
      location: ./crasher
    runner:
      location: ./runner
