version: "3"
services:
  exocom0.26.1:
    image: originate/exocom:0.26.1
    container_name: exocom0.26.1
    environment:
      ROLE: exocom
      SERVICE_ROUTES: '[{"receives":null,"role":"html-server","sends":null}]'
    restart: on-failure
  html-server:
    build:
      context: ${APP_PATH}/html-server
      dockerfile: Dockerfile.dev
    command: node ./index.js
    container_name: html-server
    ports:
    - 3000:3000
    volumes:
    - ${APP_PATH}/html-server:/mnt
    environment:
      EXOCOM_HOST: exocom0.26.1
      ROLE: html-server
    depends_on:
    - exocom0.26.1
    restart: on-failure
  mongo3.4.0:
    image: mongo:3.4.0
    container_name: mongo3.4.0
    ports:
    - 27017:27017
    volumes:
    - ${APP_PATH}/.exosphere/data/mongo:/data/db
    restart: on-failure
  todo:
    build:
      context: ${APP_PATH}/todo
      dockerfile: Dockerfile.dev
    command: node src/server.js
    container_name: todo
    volumes:
    - ${APP_PATH}/todo:/mnt
    environment:
      EXOCOM_HOST: exocom0.26.1
      MONGO: mongo3.4.0
      ROLE: todo
    depends_on:
    - exocom0.26.1
    - mongo3.4.0
    restart: on-failure
