name: app-with-external-docker-images
description: An application whose services are Dockerhub images
version: 0.0.0

dependencies:
  - name: exocom
    version: 0.24.0

services:
  public:
    external-service:
      docker-image: originate/test-web-server
