name: app-with-external-docker-images
description: An application whose services are Dockerhub images
version: 0.0.0

development:
  dependencies:
    - name: exocom
      version: 0.26.1

services:
  external-service:
    docker-image: originate/test-web-server
