version: '3'
services:
  exocom0.22.1:
    image: 'originate/exocom:0.22.1'
    command: bin/exocom
    container_name: exocom0.22.1
    environment:
      ROLE: exocom
      PORT: $EXOCOM_PORT
      SERVICE_ROUTES: '[{"role":"mongo","receives":null,"sends":null}]'
  mongo:
    build: ../mongo
    container_name: mongo
    command: node_modules/exoservice/bin/exo-js
    links:
      - 'mongo3.4.0:mongo'
    environment:
      ROLE: mongo
      EXOCOM_HOST: exocom0.22.1
      EXOCOM_PORT: $EXOCOM_PORT
      MONGO: mongo
    depends_on:
      - exocom0.22.1
      - mongo3.4.0
  mongo3.4.0:
    image: 'mongo:3.4.0'
    container_name: mongo3.4.0
    ports:
      - '27017:27017'
    volumes:
      - >-
        /Users/hugoho/.exosphere/Exosphere-application-with-a-third-party-dependency/mongo/data:/data/db
