type: test service that crashes on startup
description: generic MongoDB storage service
author: exospheredev

setup: echo "installing dependencies for 'crasher' service"
startup:
  command: ./server
  online-text: online at port

messages:
  receives:
  sends:
