type: public
description: Serves the HTML UI of the Todo app
author:

# the messages that this service will send and receive
dependency-data:
  exocom:
    sends:
    receives:

# other services this service needs to run,
# e.g. databases
local:
  dependencies:

remote:
  dependencies:

development:
  port: 3000
  scripts:
    # the command to boot up the service
    run: node ./index.js
