type: web
description: A sample service using webpack for development and nginx for production
author: exospheredev

development:
  port: 8080
  scripts:
    run: /node_modules/.bin/webpack-dev-server --host 0.0.0.0 --content-base src
    test: bin/test
