name: docker-app
description: An application that relies on dockerhub images
version: 0.0.1

services:
  public:
    local-service:
      docker_image: exospheredev/local-service
      location: ./local-service
    test:
      docker_image: originate/test-web-server
