type: {{serviceType}}
description: {{description}}
author: {{author}}

startup:
  online-text: online at port

messages:
  receives:
    - {{modelName}}.create
    - {{modelName}}.create_many
    - {{modelName}}.delete
    - {{modelName}}.list
    - {{modelName}}.read
    - {{modelName}}.update
  sends:
    - {{modelName}}.created
    - {{modelName}}.created_many
    - {{modelName}}.deleted
    - {{modelName}}.listing
    - {{modelName}}.details
    - {{modelName}}.updated

dependencies:
  - name: 'mongo'
    version: '3.4.0'
    config:
      volumes:
        - '{{EXO_DATA_PATH}}:/data/db'
      ports:
        - '27017:27017'
      online-text: 'waiting for connections'

development:
  scripts:
    run: node src/server.js
    test: node_modules/cucumber/bin/cucumber.js
