name: web
description: serves the web UI of the Todo app

startup:
  command: node app
  online-text: all systems go

messages:
  sends:
    - todo.create
    - todo.list
  receives:
    - todo.created
    - todo.listing
