type: ping-service
description:
author:

startup:
  command: node node_modules/exoservice/bin/exo-js
  online-text: online at port

messages:
  receives:
    - ping
  sends:
    - pong

dependencies:

development:
  scripts:
    run: node src/server.js
    test: /node_modules/cucumber/bin/cucumber.js
