type: ping-service
description:
author:

messages:
  receives:
    - ping
  sends:
    - pong

dependencies:

development:
  scripts:
    run: node src/server.js
    test: /node_modules/cucumber/bin/cucumber.js
