type: users-service
description: has some failing feature specs
author: exospheredev

startup:
  online-text: starting the users service

development:
  scripts:
    run: echo 'starting the users service'
    test: ./run-tests
