type: users-service
description: has some failing feature specs
author: exospheredev

startup:
  command: echo 'starting the users service'
  online-text: starting the users service

messages:
  receives:
  sends:

development:
  scripts:
    run: echo 'starting the users service'
    test: ./run-tests
