type: local-service
description: serves simple HTML pages as part of the test app
author: exospheredev

setup: yarn install
startup:
  command: node_modules/.bin/lsc server.ls
  online-text: web server running at port
restart:
  ignore:
    - "**/*.txt"


messages:
  sends:
  receives:
