type: {{serviceType}}
description: {{description}}
author: {{author}}

startup:
  command: echo "nothing to start"
  online-text: nothing to start

development:
  scripts:
    test: echo "nothing to test"
