environment:
  nodejs_version: "6.5.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - npm --version
  - yarn --version
  - bin\spec.cmd

build: off
