name: todo-app
description: An example Exosphere application
version: 0.0.1
development:
  dependencies:
  - name: exocom
    version: 0.27.0
services:
  html-server:
    location: ./html-server
  todo:
    location: ./todo
