name: todo-app
description: An example Exosphere application
version: 0.0.1
local:
  dependencies:
    exocom:
      image: originate/exocom:0.27.0
services:
  html-server:
    location: ./html-server
  todo:
    location: ./todo
