type: mongo
description: connects to a local instance of mongo
author: exospheredev

startup:
  online-text: MongoDB connected

development:
  dependencies:
    - name: 'mongo'
      version: '3.4.0'

messages:
  sends:
  receives:

development:
  scripts:
    run: node server.js
