type: mongo
description: connects to a local instance of mongo
author: exospheredev

startup:
  command: node server.js
  online-text: MongoDB connected

dependencies:
  - name: 'mongo'
    version: '3.4.0'

messages:
  sends:
  receives:
