type: mongo
description: connects to a local instance of mongo
author: exospheredev

development:
  dependencies:
    - name: 'mongo'
      version: '3.4.0'

messages:
  sends:
  receives:

development:
  scripts:
    run: node server.js
