type: crasher
description: generic MongoDB storage service which crashes on startup
author: exospheredev

startup:
  online-text: online at port

messages:
  receives:
  sends:

development:
  scripts:
    run: ./server
