version: "3"
services:
  exocom0.26.1:
    image: originate/exocom:0.26.1
    container_name: exocom0.26.1
    environment:
      ROLE: exocom
      SERVICE_ROUTES: '[{"receives":["users.listed","users.created"],"role":"external-service","sends":["users.list","users.create"]}]'
  external-service:
    image: originate/test-web-server
    container_name: external-service
    ports:
    - 5000:5000
    volumes:
    - /Users/charlesrudolph/.exosphere/app-with-external-docker-images/external-service/data:/data/db
    environment:
      EXOCOM_HOST: exocom0.26.1
      EXTERNAL_SERVICE_HOST: external-service0.1.2
      EXTERNAL_SERVICE_PORT: $EXTERNAL_SERVICE_PORT
      ROLE: external-service
    depends_on:
    - exocom0.26.1
