type: users
description: generic mongoDB storage service
author: exospheredev

startup:
  online-text: online at port

messages:
  receives:
    - mongo.list
    - mongo.create
  sends:
    - mongo.listed
    - mongo.created

development:
  scripts:
    run: node server.js
