name: Frontend
description: A sample application using webpack for frontend development
author: exospheredev
version: '1.0'

services:
  public:
    frontend-service:
      location: ./frontend-service
