name: Exosphere-application-with-a-third-party-dependency
description: For testing booting up dependencies
author: exospheredev
version: '1.0'

dependencies:
  - type: exocom
    version: 0.22.1

services:
  public:
    mongo:
      location: ./mongo
