type: html-server
description: dummy html service used for testing setup only - does not run
author: test-author

setup: yarn install
startup:
  command: echo "does not run"
  online-text: does not run

messages:
  sends:
    - todo.create
  receives:
    - todo.created

dependencies:

docker:
  ports:
    - '3000:3000'
