type: postgres
description: dummy postgres service
author: exospheredev

messages:
  sends:
  receives:

development:
  scripts:
    run: node server.js
  dependencies:
    - name: 'mongo'
      version: '3.4.0'
      config:
        volumes:
          - '{{EXO_DATA_PATH}}:/data/db'
        ports:
          - '27017:27017'
        online-text:
          'waiting for connections'
