type: web
description: serves simple HTML pages as part of the test app
author: exospheredev

messages:
  sends:
    - users.list
    - users.create
  receives:
    - users.listed
    - users.created

docker:
  ports:
    - '4000:4000'

development:
  scripts:
    run: node_modules/.bin/lsc server.ls
