name: test-app
description: Empty test application
version: 1.0.0

development:
  dependencies:
  - name: exocom
    version: 0.26.1

services:
  public:
    test-service:
      location: ./test-service
  private: {}
