version: "3"
services:
  exocom0.26.1:
    image: originate/exocom:0.26.1
    container_name: exocom0.26.1
    environment:
      ROLE: exocom
      SERVICE_ROUTES: '[{"receives":["mongo.list","mongo.create"],"role":"users","sends":["mongo.listed","mongo.created"]},{"receives":["users.listed","users.created"],"role":"web","sends":["users.list","users.create"]}]'
    restart: on-failure
  users:
    build:
      context: /Users/charlesrudolph/go/src/github.com/Originate/exosphere/example-apps/running/mongo-service
      dockerfile: Dockerfile.dev
    command: node server.js
    container_name: users
    volumes:
    - /Users/charlesrudolph/go/src/github.com/Originate/exosphere/example-apps/running/mongo-service:/mnt
    environment:
      EXOCOM_HOST: exocom0.26.1
      ROLE: users
    depends_on:
    - exocom0.26.1
    restart: on-failure
  web:
    build:
      context: /Users/charlesrudolph/go/src/github.com/Originate/exosphere/example-apps/running/web-server
      dockerfile: Dockerfile.dev
    command: node_modules/.bin/lsc server.ls
    container_name: web
    ports:
    - 3000:4000
    volumes:
    - /Users/charlesrudolph/go/src/github.com/Originate/exosphere/example-apps/running/web-server:/mnt
    environment:
      EXOCOM_HOST: exocom0.26.1
      ROLE: web
    depends_on:
    - exocom0.26.1
    restart: on-failure
