type: users
description: generic mongoDB storage service
author: exospheredev

startup:
  command: node server.js
  online-text: online at port

messages:
  receives:
    - mongo.list
    - mongo.create
  sends:
    - mongo.listed
    - mongo.created
