version: "3"
services:
  backend:
    build:
      context: /Users/charlesrudolph/go/src/github.com/Originate/exosphere/example-apps/service-external-origin-env/backend-service
      dockerfile: Dockerfile.dev
    command: node index.js
    container_name: backend
    ports:
    - 3000:3000
    volumes:
    - /Users/charlesrudolph/go/src/github.com/Originate/exosphere/example-apps/service-external-origin-env/backend-service:/mnt
    environment:
      ROLE: backend
    restart: on-failure
  frontend:
    build:
      context: /Users/charlesrudolph/go/src/github.com/Originate/exosphere/example-apps/service-external-origin-env/frontend-service
      dockerfile: Dockerfile.dev
    command: /node_modules/.bin/webpack-dev-server --host 0.0.0.0 --content-base src
    container_name: frontend
    ports:
    - 3010:8080
    volumes:
    - /Users/charlesrudolph/go/src/github.com/Originate/exosphere/example-apps/service-external-origin-env/frontend-service:/mnt
    environment:
      ROLE: frontend
    restart: on-failure
