name: tests-failing
description: Allows to run application tests
version: 1.0

development:
  dependencies:
    - name: exocom
      version: 0.26.1

services:
  public:
    tweets-service:
      location: ./tweets-service
    users-service:
      location: ./users-service
