language: node_js

sudo: required
dist: trusty

services:
  - docker

node_js:
  - "6"
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install exosphere-shared


before_script:
  - node_modules/o-tools-livescript/bin/build
  - git config --global user.email "circle@email.com"
  - git config --global user.name "circleci"


notifications:
  email: false
