type: html-server
description: dummy html service used for testing setup only - does not run
author: test-author

messages:
  sends:
    - todo.create
  receives:
    - todo.created

development:
  ports:
    - 80
  scripts:
    run: echo "does not run"
