type: html-server
description: dummy html service used for testing setup only - does not run
author: test-author

startup:
  online-text: does not run

messages:
  sends:
    - todo.create
  receives:
    - todo.created

dependencies:

docker:
  ports:
    - '3000:3000'

development:
  scripts:
    run: echo "does not run"
