language: node_js

sudo: required
dist: trusty

services:
  - docker

node_js:
  - "6"
  - "7"


before_install:
  - npm install exosphere-shared
  - docker pull originate/exocom:0.15.1
  - docker pull exospheredev/web
  - docker pull exospheredev/web-server
  - docker pull exospheredev/mongo-service
  - docker pull exospheredev/crasher
  - docker pull exospheredev/runner


before_script:
  - node_modules/o-tools-livescript/bin/build
  - git config --global user.email "circle@email.com"
  - git config --global user.name "circleci"


notifications:
  email: false
