name: application with an external service
description: skeleton app using only an external service
version: '1.0.0'

development:
  dependencies:
    - name: exocom
      version: 0.26.1


services:
  public:
    web:
      location: ../web-service
