type: users
description: generic mongoDB storage service
author: exospheredev

messages:
  receives:
    - mongo.list
    - mongo.create
  sends:
    - mongo.listed
    - mongo.created
environment:
  default:
    ENV1: value1
    ENV3: value3
  development:
    ENV2: value2
    ENV3: dev_value3
  production:
  secrets:
    - EXOSPHERE_SECRET

development:
  scripts:
    run: echo "does not run"
  dependencies:
    - name: mongo
      version: 3.4.0
