type: users
description: generic mongoDB storage service
author: exospheredev

startup:
  online-text: online at port

messages:
  receives:
    - mongo.list
    - mongo.create
  sends:
    - mongo.listed
    - mongo.created

dependencies:
  - name: mongo
    version: 3.4.0

development:
  scripts:
    run: echo "does not run"
