type: _____serviceType_____
description: _____description_____
author: _____author_____

setup: yarn install
startup:
  command: node node_modules/exoservice/bin/exo-js
  online-text: online at port
tests: node_modules/cucumber/bin/cucumber.js

messages:
  receives:
    - _____modelName_____.create
    - _____modelName_____.create_many
    - _____modelName_____.delete
    - _____modelName_____.list
    - _____modelName_____.read
    - _____modelName_____.update
  sends:
    - _____modelName_____.created
    - _____modelName_____.created_many
    - _____modelName_____.deleted
    - _____modelName_____.listing
    - _____modelName_____.details
    - _____modelName_____.updated

dependencies:
  mongo:
    version: '3.4.0'
    docker_flags:
      volume: '-v {{EXO_DATA_PATH}}:/data/db'
      online_text: 'waiting for connections'
      port: '-p 27017:27017'
