type: _____serviceType_____
description: _____description_____
author: _____author_____

setup: yarn install
startup:
  command: node node_modules/exoservice/bin/exo-js
  online-text: online at port
tests: node_modules/cucumber/bin/cucumber.js

messages:
  receives:
    - _____modelName_____.create
    - _____modelName_____.create_many
    - _____modelName_____.delete
    - _____modelName_____.list
    - _____modelName_____.read
    - _____modelName_____.update
  sends:
    - _____modelName_____.created
    - _____modelName_____.created_many
    - _____modelName_____.deleted
    - _____modelName_____.listing
    - _____modelName_____.details
    - _____modelName_____.updated

dependencies:
  - name: 'mongo'
    version: '3.4.0'
    config:
      volumes:
        - '{{EXO_DATA_PATH}}:/data/db'
      ports:
        - '27017:27017'
      online-text: 'waiting for connections'
