name: application-with-end-to-end-tests
description: Allows to run application tests
version: 1.0

development:
  dependencies:
    - name: exocom
      version: 0.22.1

services:
  public:
    exoservice:
      location: ./exoservice
