name: Example application
description: Demonstrates basic Exosphere application startup
version: '1.0'

dependencies:
  - name: exocom
    version: 0.24.0

services:
  public:
    crasher:
      location: ./crasher
    runner:
      location: ./runner
