name: Example application
description: Demonstrates basic Exosphere application startup
version: '1.0'

development:
  dependencies:
    - name: exocom
      version: 0.26.1

services:
  public:
    crasher:
      location: ./crasher
    runner:
      location: ./runner
