type: tweets-service
description: has some passing feature specs
author: exospheredev

startup:
  command: echo 'starting the tweets service'
  online-text: starting the tweets service
tests: echo 'running tests for tweets service'

messages:
  receives:
  sends:
