type: tweets-service
description: has some passing feature specs
author: exospheredev

startup:
  command: echo 'starting the tweets service'
  online-text: starting the tweets service

messages:
  receives:
  sends:

development:
  scripts:
    run: echo 'starting the tweets service'
    test: echo 'running tests for tweets service'
